version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: support_bot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - .dev/db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

volumes:
  pg_data: null
